// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAAFVrOY9knGR0YyKQRps3C1LQzRYx2u0',
    appId: '1:247146308801:web:659ecf0ff53751c38ee040',
    messagingSenderId: '247146308801',
    projectId: 'appauth-cbd5f',
    authDomain: 'appauth-cbd5f.firebaseapp.com',
    storageBucket: 'appauth-cbd5f.appspot.com',
    measurementId: 'G-K85J68T19M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxJOyCCF53wj7nAfA0ZIBOhZnVTpbqvdQ',
    appId: '1:247146308801:android:87b8343d079bf4e58ee040',
    messagingSenderId: '247146308801',
    projectId: 'appauth-cbd5f',
    storageBucket: 'appauth-cbd5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmufELU7g3YPbIpeMEuHNbxzlxT7vjLMQ',
    appId: '1:247146308801:ios:2022d775f4727c9e8ee040',
    messagingSenderId: '247146308801',
    projectId: 'appauth-cbd5f',
    storageBucket: 'appauth-cbd5f.appspot.com',
    iosBundleId: 'com.example.loginfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmufELU7g3YPbIpeMEuHNbxzlxT7vjLMQ',
    appId: '1:247146308801:ios:2022d775f4727c9e8ee040',
    messagingSenderId: '247146308801',
    projectId: 'appauth-cbd5f',
    storageBucket: 'appauth-cbd5f.appspot.com',
    iosBundleId: 'com.example.loginfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAAFVrOY9knGR0YyKQRps3C1LQzRYx2u0',
    appId: '1:247146308801:web:28787c7acf50a0af8ee040',
    messagingSenderId: '247146308801',
    projectId: 'appauth-cbd5f',
    authDomain: 'appauth-cbd5f.firebaseapp.com',
    storageBucket: 'appauth-cbd5f.appspot.com',
    measurementId: 'G-FXX2NT33RH',
  );
}
